Greeting.create(message: 'Hello world!')
Greeting.create(message: 'How are you?')
Greeting.create(message: 'Welcome to our blog.')
Greeting.create(message: 'Your one-stop shop.')
Greeting.create(message: 'What would you like today?')
